table Fact_Sales
	lineageTag: 3f14fae4-b5b6-4296-bd12-713655ab31af

	measure 'Total Sales' =
			
			SUM ( Fact_Sales[sales_amount] )
		lineageTag: 64943e14-1039-4405-8293-3c7267774ae3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MoM Growth %' =
			
			VAR PreviousMonthSales =
			    CALCULATE (
			        [Total Sales],
			        PREVIOUSMONTH ( 'Dim_Date'[Date] )
			    )
			RETURN
			    DIVIDE (
			        [Total Sales] - PreviousMonthSales,
			        PreviousMonthSales
			    )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 3f142093-08d7-4284-a021-ae37b99c21c2

	measure 'Running Total Sales' =
			
			CALCULATE (
			    [Total Sales],
			    DATESYTD ( 'Dim_Date'[Date] )
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: fdae37e5-e4a6-4707-83d3-8fa71ca8cbd6

	measure 'Average Sale Value' =
			
			AVERAGE ( Fact_Sales[sales_amount] )
		lineageTag: 69c65ba4-b096-4d16-bac9-884956a0880b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Item Sales Rank' =
			
			RANKX (
			    ALL ( 'Dim_Product'[Item] ),
			    [Total Sales],
			    ,
			    DESC
			)
		formatString: 0
		lineageTag: fb53fc80-7080-4a55-99c2-92907bfefbe4

	column sale_id
		dataType: int64
		formatString: 0
		lineageTag: 36cc02ae-bdac-4f35-a1db-f0ed47ef5c4a
		summarizeBy: sum
		sourceColumn: sale_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 57dc150c-eca3-426b-9ec3-231c06d38b6b
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column city
		dataType: string
		lineageTag: 218d1e63-540a-4e3a-88cc-16371b80a47a
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column store_format
		dataType: string
		lineageTag: 6b4e44f8-aae3-4033-a193-8c5f7383b74c
		summarizeBy: none
		sourceColumn: store_format

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 15067027-0576-4476-9880-49d48e0c35bd
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column item
		dataType: string
		lineageTag: 9fea65af-9620-49b9-b677-a185263251b9
		summarizeBy: none
		sourceColumn: item

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: 275e21b6-87b0-4af3-a328-02b5a04463b6
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: double
		lineageTag: 2a05a19c-abad-4eff-b0e4-f0d40d797a5a
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sales_amount
		dataType: double
		lineageTag: a9d9ff14-0d43-4d43-881a-5f3482477c44
		summarizeBy: sum
		sourceColumn: sales_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Product_Key
		dataType: string
		lineageTag: 6de765f6-d8fc-47c3-9ca1-50a9fc36b919
		summarizeBy: none
		sourceColumn: Product_Key

		annotation SummarizationSetBy = Automatic

	partition Fact_Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\piriyadharshini\Downloads\brewmetrics_sales.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sale_id", Int64.Type}, {"date", type date}, {"city", type text}, {"store_format", type text}, {"category", type text}, {"item", type text}, {"quantity", Int64.Type}, {"unit_price", type number}, {"sales_amount", type number}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Product_Key", each [category] & "|" & [item] & "|" & [store_format])
				in
				    #"Added Custom"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

